# Generated by Django 3.1.2 on 2020-11-30 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petfinder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CardItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('form', models.CharField(choices=[('checkbox', 'checkbox'), ('text', 'text')], max_length=200)),
            ],
        ),
    ]
