# Generated by Django 3.1.2 on 2020-11-30 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petfinder', '0002_card_carditem'),
    ]

    operations = [
        migrations.AddField(
            model_name='carditem',
            name='image',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='carditem',
            name='form',
            field=models.CharField(choices=[('checkbox', 'checkbox'), ('text', 'text')], default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='carditem',
            name='name',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
