# Generated by Django 3.1.2 on 2020-11-30 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('petfinder', '0003_auto_20201130_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='carditem',
            name='card',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='petfinder.card'),
        ),
    ]
