name: 447-Petfinder CI

on:
  push:
    branches: 
      - main
      - development
  pull_request:
    branches:
      - main
      - development

jobs:
  build:
    env:
      PETSITE_SECRET_KEY: ${{secrets.PETSITE_SECRET_KEY}} 
      PETFINDER_SECRET_KEY: ${{secrets.PETFINDER_SECRET_KEY}} 
      PETFINDER_KEY: ${{secrets.PETFINDER_KEY}} 
      ACCESS_KEY: ${{secrets.ACCESS_KEY}} 
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        pytest tests/test_html.py
        pytest tests/test_query.py
        pytest tests/test_style.py
